# Generated by Django 3.2 on 2021-05-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210531_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tittle',
            new_name='title',
        ),
    ]
